"""seed 5 new presentiel formations: no-code, IA, community, video, branding

Revision ID: 20260417_0022
Revises: 20260417_0021
Create Date: 2026-04-17 00:00:00.000000
"""

import json
from alembic import op
import sqlalchemy as sa

revision = "20260417_0022"
down_revision = "20260417_0021"
branch_labels = None
depends_on = None


FORMATIONS = [
    {
        "slug": "no-code-creez-vos-applications",
        "title": "No-Code : Créez vos applications web sans une seule ligne de code",
        "category": "No-Code & Tech",
        "level": "Tous niveaux",
        "image": "/Flyers/Figma-Image.jpg",
        "format_type": "presentiel",
        "dashboard_type": "guided",
        "session_label": "Prochaine session : 20 mai 2026",
        "current_price_amount": 85000,
        "original_price_amount": 110000,
        "price_currency": "XAF",
        "allow_installments": True,
        "rating": 4.7,
        "reviews": 42,
        "badges": json.dumps(["premium", "populaire"]),
        "is_featured_home": False,
        "home_feature_rank": 60,
        "intro": "En 4 semaines de formation intensive en présentiel, apprenez à concevoir et lancer des applications web, des sites e-commerce et des outils internes sans écrire une seule ligne de code. Bubble, Webflow, Notion, Glide, Make — vous maîtriserez l'écosystème no-code le plus puissant du marché.",
        "mentor_name": "Francis Kenne",
        "mentor_label": "Responsable académique",
        "mentor_image": "/Teams/photo-fk.jpg",
        "included_items": json.dumps([
            {"text": "4 semaines de cours en présentiel (20h/semaine)"},
            {"text": "Accès aux outils no-code pendant 6 mois"},
            {"text": "1 projet réel déployé en fin de formation"},
            {"text": "Suivi individuel et sessions de débogage"},
            {"text": "Certificat de compétence no-code"},
            {"text": "Accès à la communauté alumni"},
        ]),
        "objective_items": json.dumps([
            {"text": "Concevoir une application web fonctionnelle avec Bubble"},
            {"text": "Créer un site professionnel animé avec Webflow"},
            {"text": "Automatiser des flux de travail avec Make (ex-Integromat)"},
            {"text": "Connecter des APIs sans code via des outils visuels"},
            {"text": "Lancer un MVP en moins de 30 jours"},
            {"text": "Monétiser vos compétences no-code en freelance"},
        ]),
        "project_items": json.dumps([
            {"title": "App de réservation", "description": "Créez une application de prise de rendez-vous avec paiement intégré sur Bubble."},
            {"title": "Site portfolio animé", "description": "Déployez un portfolio professionnel avec interactions avancées sur Webflow."},
            {"title": "Bot d'automatisation", "description": "Construisez un système de notification automatique reliant Gmail, Notion et WhatsApp via Make."},
        ]),
        "audience_text": "Cette formation s'adresse aux entrepreneurs, marketeurs, designers et toute personne souhaitant concrétiser ses idées numériques sans dépendre d'un développeur. Aucune connaissance technique préalable n'est requise.",
        "certificate_copy": "À l'issue de cette formation, vous recevez le certificat « No-Code Builder » de l'Académie des Créatifs, attestant de votre capacité à concevoir et déployer des applications web sans code. Ce certificat est reconnu par nos partenaires employeurs et agences digitales.",
        "certificate_image": "/certificat-academie.png",
        "module_items": json.dumps([
            {"title": "Semaine 1 — Fondations No-Code", "lessons": [
                {"title": "Présentation de l'écosystème no-code 2025"},
                {"title": "Bubble : structure d'une app, base de données visuelle"},
                {"title": "Webflow : blocs, styles et responsive"},
                {"title": "Atelier : votre première page web sans code"},
            ]},
            {"title": "Semaine 2 — Bubble : logique et interactions", "lessons": [
                {"title": "Workflows, conditions et actions"},
                {"title": "Gestion des utilisateurs et authentification"},
                {"title": "Paiements en ligne avec Stripe / Mobile Money"},
                {"title": "Projet : mini-marketplace ou app de réservation"},
            ]},
            {"title": "Semaine 3 — Automatisation avec Make", "lessons": [
                {"title": "Scénarios d'automatisation : triggers et actions"},
                {"title": "Connexion d'apps tierces (Gmail, Notion, Airtable)"},
                {"title": "Webhooks et API REST sans code"},
                {"title": "Atelier : automatisation d'un CRM simplifié"},
            ]},
            {"title": "Semaine 4 — Lancement et freelance", "lessons": [
                {"title": "Déploiement, SEO et performance"},
                {"title": "Présenter et vendre votre app à un client"},
                {"title": "Tarification et gestion de projet no-code"},
                {"title": "Soutenance : présentation de votre projet final"},
            ]},
        ]),
        "faq_items": json.dumps([
            {"question": "Faut-il savoir programmer ?", "answer": "Absolument pas. Le no-code est précisément conçu pour créer sans écrire de code. Seule une aisance avec les outils numériques de base est recommandée."},
            {"question": "Quels outils utilise-t-on pendant la formation ?", "answer": "Bubble, Webflow, Make, Glide, Notion et Airtable. Tous disposent d'une version gratuite pour pratiquer."},
            {"question": "Peut-on vraiment gagner de l'argent avec le no-code ?", "answer": "Oui. De nombreux freelances facturent entre 300 000 et 1 500 000 FCFA par projet no-code. La demande est forte et l'offre encore rare en Afrique."},
            {"question": "La formation est-elle en présentiel uniquement ?", "answer": "Oui, cette version est 100% présentielle. Les séances sont enregistrées pour les absences exceptionnelles."},
        ]),
    },
    {
        "slug": "maitrisez-ia-chatgpt-claude-gemini",
        "title": "Maîtrisez l'Intelligence Artificielle : ChatGPT, Claude, Gemini & les outils du futur",
        "category": "Intelligence Artificielle",
        "level": "Tous niveaux",
        "image": "/Flyers/strategy.webp",
        "format_type": "presentiel",
        "dashboard_type": "guided",
        "session_label": "Prochaine session : 03 juin 2026",
        "current_price_amount": 75000,
        "original_price_amount": 95000,
        "price_currency": "XAF",
        "allow_installments": True,
        "rating": 4.9,
        "reviews": 28,
        "badges": json.dumps(["premium", "populaire"]),
        "is_featured_home": False,
        "home_feature_rank": 70,
        "intro": "L'IA n'est plus une option — c'est un avantage concurrentiel. En 3 semaines de formation pratique en présentiel, apprenez à utiliser ChatGPT, Claude, Gemini, Midjourney et les APIs d'OpenAI pour automatiser votre travail, produire du contenu, générer des visuels et construire des produits intelligents.",
        "mentor_name": "Francis Kenne",
        "mentor_label": "Responsable académique",
        "mentor_image": "/Teams/photo-fk.jpg",
        "included_items": json.dumps([
            {"text": "3 semaines de cours en présentiel (18h/semaine)"},
            {"text": "Accès aux comptes premium ChatGPT & Claude pendant la formation"},
            {"text": "Guide de prompts avancés (100+ templates)"},
            {"text": "Projets pratiques sur des cas réels"},
            {"text": "Certificat « AI Practitioner » de l'Académie des Créatifs"},
            {"text": "Accès à vie aux mises à jour du contenu"},
        ]),
        "objective_items": json.dumps([
            {"text": "Maîtriser le prompt engineering pour ChatGPT, Claude et Gemini"},
            {"text": "Générer des visuels professionnels avec Midjourney et DALL·E"},
            {"text": "Automatiser la production de contenu (posts, articles, scripts)"},
            {"text": "Utiliser l'API OpenAI pour construire des mini-outils IA"},
            {"text": "Intégrer l'IA dans un workflow créatif ou business"},
            {"text": "Comprendre les limites et bonnes pratiques éthiques de l'IA"},
        ]),
        "project_items": json.dumps([
            {"title": "Assistant de contenu IA", "description": "Créez un système de génération automatique de posts, légendes et newsletters pour les réseaux sociaux."},
            {"title": "Pipeline de création visuelle", "description": "Construisez un flux de production d'images publicitaires avec Midjourney + retouche Photoshop assistée par IA."},
            {"title": "Mini-chatbot personnalisé", "description": "Déployez un chatbot répondant aux questions de vos clients en utilisant l'API Claude ou OpenAI."},
        ]),
        "audience_text": "Cette formation est faite pour les créatifs, entrepreneurs, marketeurs et professionnels qui veulent utiliser l'IA comme levier de productivité et d'innovation. Aucune connaissance en programmation n'est nécessaire pour la majorité du programme.",
        "certificate_copy": "En fin de formation, vous obtenez le certificat « AI Practitioner » de l'Académie des Créatifs, validant votre capacité à intégrer les outils d'intelligence artificielle dans un contexte professionnel et créatif.",
        "certificate_image": "/certificat-academie.png",
        "module_items": json.dumps([
            {"title": "Semaine 1 — Comprendre et maîtriser les LLMs", "lessons": [
                {"title": "Comment fonctionnent ChatGPT, Claude et Gemini ?"},
                {"title": "Prompt engineering : structure, rôles et contexte"},
                {"title": "Prompts avancés : chain-of-thought, few-shot, role prompting"},
                {"title": "Atelier : 20 cas d'usage concrets en design et business"},
            ]},
            {"title": "Semaine 2 — IA générative pour les créatifs", "lessons": [
                {"title": "Midjourney : génération d'images, styles et paramètres avancés"},
                {"title": "DALL·E et Firefly : intégration dans Photoshop"},
                {"title": "Génération de vidéos courtes avec Runway et Kling"},
                {"title": "Projet : campagne publicitaire 100% générée par IA"},
            ]},
            {"title": "Semaine 3 — Construire avec l'IA", "lessons": [
                {"title": "Introduction à l'API OpenAI et l'API Claude"},
                {"title": "Créer un assistant personnalisé (GPT / Claude Project)"},
                {"title": "Automatisation IA avec Make et Zapier"},
                {"title": "Soutenance : présentation de votre projet IA"},
            ]},
        ]),
        "faq_items": json.dumps([
            {"question": "Quelle est la différence entre ChatGPT, Claude et Gemini ?", "answer": "Ce sont trois assistants IA de sociétés différentes (OpenAI, Anthropic, Google). Chacun a ses forces : ChatGPT est polyvalent, Claude excelle en rédaction et analyse longue, Gemini est fort pour la recherche et l'intégration Google. Vous les comparerez tous en formation."},
            {"question": "Faut-il un compte payant ChatGPT ou Claude ?", "answer": "L'Académie fournit des accès premium pendant les 3 semaines de formation. Après, les versions gratuites suffisent pour pratiquer la majorité des exercices."},
            {"question": "L'IA va-t-elle remplacer les graphistes et créatifs ?", "answer": "Non — elle va amplifier vos capacités. Les créatifs qui maîtrisent l'IA produisent 5x plus vite. Ceux qui l'ignorent seront désavantagés. Cette formation vous met du bon côté."},
            {"question": "Peut-on suivre cette formation sans être créatif ?", "answer": "Oui. Les applications de l'IA touchent toutes les industries. Entrepreneurs, commerciaux, enseignants — tous ont quelque chose à gagner ici."},
        ]),
    },
    {
        "slug": "community-management-personal-branding",
        "title": "Community Management & Personal Branding : Bâtissez votre empire digital",
        "category": "Marketing Digital",
        "level": "Débutant à intermédiaire",
        "image": "/Flyers/10000abonnes.jpg",
        "format_type": "presentiel",
        "dashboard_type": "guided",
        "session_label": "Prochaine session : 27 mai 2026",
        "current_price_amount": 65000,
        "original_price_amount": None,
        "price_currency": "XAF",
        "allow_installments": False,
        "rating": 4.5,
        "reviews": 67,
        "badges": json.dumps(["populaire"]),
        "is_featured_home": False,
        "home_feature_rank": 80,
        "intro": "Instagram, TikTok, LinkedIn — ces plateformes sont aujourd'hui de vraies machines à opportunités pour qui sait les utiliser. Cette formation de 3 semaines vous apprend à créer du contenu engageant, à gérer des communautés, à développer votre marque personnelle et à monétiser votre présence en ligne.",
        "mentor_name": "Natchi Dylan",
        "mentor_label": "Responsable des formations",
        "mentor_image": "/Teams/photo-natchi.jpg",
        "included_items": json.dumps([
            {"text": "3 semaines de cours en présentiel"},
            {"text": "Templates de contenu Canva (50+ designs)"},
            {"text": "Calendrier éditorial prêt à l'emploi"},
            {"text": "Accès aux outils de planification (Buffer, Metricool)"},
            {"text": "Certificat Community Manager de l'Académie des Créatifs"},
            {"text": "1 session de coaching individuel"},
        ]),
        "objective_items": json.dumps([
            {"text": "Définir et incarner une identité de marque forte sur les réseaux"},
            {"text": "Créer du contenu viral adapté à chaque plateforme"},
            {"text": "Gérer et animer une communauté engagée"},
            {"text": "Analyser les statistiques et optimiser sa stratégie"},
            {"text": "Monétiser son audience (sponsoring, produits digitaux, services)"},
            {"text": "Produire des reels, stories et posts avec Canva et CapCut"},
        ]),
        "project_items": json.dumps([
            {"title": "Identité de marque digitale", "description": "Créez une charte visuelle complète pour votre personal brand ou celle d'un client."},
            {"title": "Calendrier éditorial 30 jours", "description": "Planifiez et pré-produisez un mois de contenu multi-plateformes cohérent et engageant."},
            {"title": "Campagne de lancement", "description": "Orchestrez une campagne de lancement de produit ou service sur Instagram et TikTok avec analyse de résultats."},
        ]),
        "audience_text": "Idéal pour les entrepreneurs, freelances créatifs, responsables communication et toute personne souhaitant développer sa visibilité ou gérer les réseaux sociaux d'une marque ou d'un client. Aucun prérequis technique.",
        "certificate_copy": "À l'issue de la formation, vous recevez le certificat « Community Manager » de l'Académie des Créatifs, attestant de vos compétences en gestion de communauté, création de contenu et stratégie digitale.",
        "certificate_image": "/certificat-academie.png",
        "module_items": json.dumps([
            {"title": "Semaine 1 — Personal Branding & Stratégie", "lessons": [
                {"title": "Définir son positionnement et son identité de marque"},
                {"title": "Connaître son audience cible (persona)"},
                {"title": "Stratégie de contenu par plateforme : Instagram, TikTok, LinkedIn"},
                {"title": "Atelier : création de votre charte visuelle digitale"},
            ]},
            {"title": "Semaine 2 — Création de contenu & Production", "lessons": [
                {"title": "Canva avancé : templates, animations et brandkit"},
                {"title": "CapCut : montage vidéo pour reels et TikTok"},
                {"title": "Copywriting : accroches, légendes et CTA"},
                {"title": "Atelier : production de 10 posts prêts à publier"},
            ]},
            {"title": "Semaine 3 — Growth & Monétisation", "lessons": [
                {"title": "Algorithmes et growth hacking organique"},
                {"title": "Publicité Meta (Facebook & Instagram Ads) — notions"},
                {"title": "Monétisation : affiliate, sponsoring, vente de services"},
                {"title": "Analyse des KPIs et optimisation continue"},
            ]},
        ]),
        "faq_items": json.dumps([
            {"question": "Faut-il déjà avoir une audience ?", "answer": "Non. La formation part de zéro et vous aide à construire votre présence depuis le début, avec des méthodes testées et éprouvées."},
            {"question": "Apprend-on à gérer les réseaux pour des clients ?", "answer": "Oui. Le programme couvre aussi bien le personal branding que la gestion de comptes clients, avec facturation et reporting."},
            {"question": "Travaille-t-on sur Instagram, TikTok ou les deux ?", "answer": "Les deux, plus LinkedIn. Chaque plateforme a sa propre logique de contenu et vous apprendrez à adapter votre stratégie."},
        ]),
    },
    {
        "slug": "montage-video-premiere-pro-davinci",
        "title": "Montage Vidéo Professionnel : Premiere Pro & DaVinci Resolve de A à Z",
        "category": "Vidéo & Motion",
        "level": "Débutant à avancé",
        "image": "/Flyers/flyer-motion.jpg",
        "format_type": "presentiel",
        "dashboard_type": "guided",
        "session_label": "Prochaine session : 10 juin 2026",
        "current_price_amount": 80000,
        "original_price_amount": 105000,
        "price_currency": "XAF",
        "allow_installments": True,
        "rating": 4.6,
        "reviews": 53,
        "badges": json.dumps(["premium"]),
        "is_featured_home": False,
        "home_feature_rank": 90,
        "intro": "Du tournage au rendu final, maîtrisez les deux logiciels de montage les plus utilisés dans l'industrie audiovisuelle. En 4 semaines de formation présentielle intensive, vous apprenez à monter des courts-métrages, des publicités, des clips musicaux et des contenus pour les réseaux sociaux.",
        "mentor_name": "Francis Kenne",
        "mentor_label": "Responsable académique",
        "mentor_image": "/Teams/photo-fk.jpg",
        "included_items": json.dumps([
            {"text": "4 semaines de cours pratiques en présentiel"},
            {"text": "Accès aux licences Adobe Creative Cloud pendant la formation"},
            {"text": "DaVinci Resolve (gratuit, fourni)"},
            {"text": "Pack de 20 Go de ressources (musiques, effets, LUTs)"},
            {"text": "Certificat Montage Vidéo de l'Académie des Créatifs"},
            {"text": "Portfolio de 3 projets finalisés"},
        ]),
        "objective_items": json.dumps([
            {"text": "Maîtriser l'interface et le workflow de Premiere Pro"},
            {"text": "Effectuer un étalonnage colorimétrique professionnel sur DaVinci Resolve"},
            {"text": "Monter des publicités, clips et courts-métrages"},
            {"text": "Créer des transitions, titres animés et effets visuels basiques"},
            {"text": "Exporter pour YouTube, Instagram, TikTok et la diffusion TV"},
            {"text": "Travailler en équipe sur un projet multitrack"},
        ]),
        "project_items": json.dumps([
            {"title": "Publicité de 30 secondes", "description": "Montez une publicité produit complète avec transitions, musique, voice-over et motion titles."},
            {"title": "Court-métrage documentaire", "description": "Réalisez un mini-documentaire de 3 minutes avec interviews, b-roll et étalonnage cinématique sur DaVinci."},
            {"title": "Reel de présentation", "description": "Produisez votre reel professionnel mettant en valeur vos 3 meilleurs projets pour décrocher des clients."},
        ]),
        "audience_text": "Cette formation est destinée aux passionnés de vidéo, youtubers, créateurs de contenu, communicants et professionnels de l'image. Débutants acceptés — un niveau basique en informatique suffit.",
        "certificate_copy": "À la fin de la formation, vous obtenez le certificat « Monteur Vidéo » de l'Académie des Créatifs, validant votre maîtrise de Premiere Pro et DaVinci Resolve sur des projets réels.",
        "certificate_image": "/certificat-academie.png",
        "module_items": json.dumps([
            {"title": "Semaine 1 — Fondamentaux du montage", "lessons": [
                {"title": "Comprendre le langage audiovisuel"},
                {"title": "Premiere Pro : import, timeline, raccourcis clavier essentiels"},
                {"title": "Montage basique : coupes, transitions, synchronisation audio"},
                {"title": "Atelier : montage d'un clip de 60 secondes"},
            ]},
            {"title": "Semaine 2 — Montage avancé & motion", "lessons": [
                {"title": "Multicam, proxies et gestion de projets volumineux"},
                {"title": "Titres animés avec Adobe Essential Graphics"},
                {"title": "Intégration avec After Effects : motion graphics basiques"},
                {"title": "Effets et masques dans Premiere Pro"},
            ]},
            {"title": "Semaine 3 — DaVinci Resolve & étalonnage", "lessons": [
                {"title": "Découverte de DaVinci : interface et navigation"},
                {"title": "Color grading : roues chromatiques, courbes, LUTs"},
                {"title": "Skin tones et correspondance de couleurs entre plans"},
                {"title": "Atelier : étalonnage d'une séquence documentaire"},
            ]},
            {"title": "Semaine 4 — Export, diffusion & carrière", "lessons": [
                {"title": "Formats d'export selon la destination (web, TV, cinéma)"},
                {"title": "Optimisation pour YouTube, Instagram et TikTok"},
                {"title": "Tarification et gestion de projet vidéo en freelance"},
                {"title": "Soutenance : présentation des projets finaux"},
            ]},
        ]),
        "faq_items": json.dumps([
            {"question": "Faut-il apporter son propre ordinateur ?", "answer": "Oui, un ordinateur portable ou fixe avec minimum 16 Go de RAM est recommandé. L'Académie met aussi à disposition des postes équipés pendant les séances."},
            {"question": "Quelle est la différence entre Premiere Pro et DaVinci ?", "answer": "Premiere Pro (Adobe) est le standard en agence et en broadcast. DaVinci Resolve (Blackmagic) est le roi de l'étalonnage cinéma, utilisé dans Hollywood. Les deux sont enseignés dans cette formation."},
            {"question": "Peut-on vivre du montage vidéo en Afrique ?", "answer": "Absolument. La demande explose : publicités, clips, YouTube, réseaux sociaux. Les bons monteurs facturent 50 000 à 300 000 FCFA par projet."},
        ]),
    },
    {
        "slug": "photoshop-maitrise-totale",
        "title": "Photoshop Maîtrise Totale : Retouche, Manipulation & Création Graphique Pro",
        "category": "Design Graphique",
        "level": "Débutant à avancé",
        "image": "/Flyers/sb1.jpg",
        "format_type": "presentiel",
        "dashboard_type": "guided",
        "session_label": "Prochaine session : 29 avril 2026",
        "current_price_amount": 70000,
        "original_price_amount": 90000,
        "price_currency": "XAF",
        "allow_installments": False,
        "rating": 4.8,
        "reviews": 119,
        "badges": json.dumps(["populaire", "promo"]),
        "is_featured_home": False,
        "home_feature_rank": 100,
        "intro": "Photoshop est l'outil incontournable de tout professionnel de l'image. En 3 semaines de formation présentielle, passez du niveau débutant à un niveau professionnel confirmé : retouche photo, manipulation d'images, création de visuels publicitaires et intégration IA. La maîtrise totale, sans compromis.",
        "mentor_name": "Bihee Alex",
        "mentor_label": "Formateur",
        "mentor_image": "/Teams/photo-Alex-Bihee.jpg",
        "included_items": json.dumps([
            {"text": "3 semaines de cours en présentiel (18h/semaine)"},
            {"text": "Accès Adobe Creative Cloud pendant la formation"},
            {"text": "Pack de ressources : brushes, presets, mockups, textures"},
            {"text": "Exercices corrigés pour chaque module"},
            {"text": "Certificat Photoshop de l'Académie des Créatifs"},
            {"text": "Portfolio de 5 projets finalisés"},
        ]),
        "objective_items": json.dumps([
            {"text": "Maîtriser les calques, masques et modes de fusion"},
            {"text": "Retoucher des portraits et des produits comme un professionnel"},
            {"text": "Créer des compositions et montages photoréalistes"},
            {"text": "Utiliser les outils IA de Photoshop (Firefly, Generative Fill)"},
            {"text": "Concevoir des affiches, flyers et visuels publicitaires"},
            {"text": "Préparer et exporter des fichiers pour l'impression et le web"},
        ]),
        "project_items": json.dumps([
            {"title": "Campagne publicitaire", "description": "Créez une série de 3 visuels cohérents pour une marque fictive : affiche, post Instagram et bannière web."},
            {"title": "Manipulation photoréaliste", "description": "Réalisez un montage complexe intégrant plusieurs photos, textures, effets lumineux et éléments graphiques."},
            {"title": "Retouche beauté & packshot", "description": "Retouchez un portrait et un packshot produit aux standards des magazines et catalogues professionnels."},
        ]),
        "audience_text": "Cette formation est ouverte à tous : graphistes autodidactes souhaitant combler leurs lacunes, professionnels du marketing, photographes et toute personne désirant maîtriser le logiciel de retouche numéro 1 au monde.",
        "certificate_copy": "En fin de parcours, vous obtenez le certificat « Photoshop Expert » de l'Académie des Créatifs, validant votre maîtrise du logiciel et votre capacité à produire des visuels professionnels pour des clients réels.",
        "certificate_image": "/certificat-academie.png",
        "module_items": json.dumps([
            {"title": "Semaine 1 — Fondations Photoshop", "lessons": [
                {"title": "Interface, workspace et raccourcis essentiels"},
                {"title": "Calques, groupes et organisation d'un document complexe"},
                {"title": "Sélections avancées : lasso, baguette, sélection par couleur, IA"},
                {"title": "Masques de calque et masques vectoriels"},
            ]},
            {"title": "Semaine 2 — Retouche & Manipulation", "lessons": [
                {"title": "Retouche portrait : peau, yeux, dents, cheveux"},
                {"title": "Modes de fusion et effets lumineux créatifs"},
                {"title": "Détourage professionnel (cheveux, fumée, transparence)"},
                {"title": "Montage photoréaliste : ombres, perspectives, cohérence lumineuse"},
            ]},
            {"title": "Semaine 3 — Création graphique & IA", "lessons": [
                {"title": "Typographie et mise en page dans Photoshop"},
                {"title": "Création d'affiches et flyers publicitaires"},
                {"title": "Generative Fill et Firefly : IA générative dans Photoshop"},
                {"title": "Export et préparation fichiers pour impression et digital"},
            ]},
        ]),
        "faq_items": json.dumps([
            {"question": "Cette formation est-elle adaptée aux vrais débutants ?", "answer": "Oui. Le programme commence de zéro. Même si vous n'avez jamais ouvert Photoshop, vous atteindrez un niveau professionnel en 3 semaines grâce au rythme intensif et au suivi individualisé."},
            {"question": "Quelle version de Photoshop utilise-t-on ?", "answer": "La dernière version d'Adobe Creative Cloud, avec toutes les fonctionnalités IA (Generative Fill, Firefly). L'Académie fournit les licences pendant la formation."},
            {"question": "En quoi ce cours est-il différent des tutoriels YouTube ?", "answer": "La formation est structurée de manière progressive, encadrée par un formateur et ponctuée de projets réels corrigés. Vous apprenez à penser comme un professionnel, pas seulement à copier des techniques."},
        ]),
    },
]


def upgrade() -> None:
    formations_table = sa.table(
        "formations",
        sa.column("slug", sa.String),
        sa.column("title", sa.String),
        sa.column("category", sa.String),
        sa.column("level", sa.String),
        sa.column("image", sa.String),
        sa.column("format_type", sa.String),
        sa.column("dashboard_type", sa.String),
        sa.column("session_label", sa.String),
        sa.column("current_price_amount", sa.Integer),
        sa.column("original_price_amount", sa.Integer),
        sa.column("price_currency", sa.String),
        sa.column("allow_installments", sa.Boolean),
        sa.column("rating", sa.Float),
        sa.column("reviews", sa.Integer),
        sa.column("badges", sa.JSON),
        sa.column("is_featured_home", sa.Boolean),
        sa.column("home_feature_rank", sa.Integer),
        sa.column("intro", sa.Text),
        sa.column("mentor_name", sa.String),
        sa.column("mentor_label", sa.String),
        sa.column("mentor_image", sa.String),
        sa.column("included_items", sa.JSON),
        sa.column("objective_items", sa.JSON),
        sa.column("project_items", sa.JSON),
        sa.column("audience_text", sa.Text),
        sa.column("certificate_copy", sa.Text),
        sa.column("certificate_image", sa.String),
        sa.column("module_items", sa.JSON),
        sa.column("faq_items", sa.JSON),
    )

    op.bulk_insert(formations_table, FORMATIONS)


def downgrade() -> None:
    slugs = [f["slug"] for f in FORMATIONS]
    placeholders = ", ".join(f"'{s}'" for s in slugs)
    op.execute(sa.text(f"DELETE FROM formations WHERE slug IN ({placeholders})"))
